version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    networks:
      - postgres-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "nathanlusa@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "postgres"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - postgres-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
