# Generated by Django 3.0.6 on 2020-05-05 21:04

import core.common.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[
                 (0, 'Inactive'), (1, 'Active')], default=core.common.enums.StatusTypes['ACTIVE'])),
                ('type', models.IntegerField(choices=[(0, 'Checking Account'), (1, 'Money'), (
                    2, 'Other')], default=core.common.enums.AccountTypes['CA'])),
                ('opening_balance', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('opening_type', models.IntegerField(choices=[
                 (0, 'Negative'), (1, 'Positive')], default=core.common.enums.MovementTypes['POSITIVE'])),
                ('opening_balance_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[
                 (0, 'Inactive'), (1, 'Active')], default=core.common.enums.StatusTypes['ACTIVE'])),
                ('movement_type', models.IntegerField(
                    choices=[(0, 'Negative'), (1, 'Positive')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('observation', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='transactions', to='core.Account')),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='core.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
