# Generated by Django 3.0.6 on 2020-05-18 11:20

import core.common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='movement_type',
            field=models.IntegerField(choices=[(0, 'Negative'), (1, 'Positive')], default=core.common.enums.MovementTypes['POSITIVE']),
        ),
    ]
