# Generated by Django 3.0.6 on 2020-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200518_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=25),
        ),
    ]
