# Generated by Django 3.0.7 on 2020-07-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200702_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_destinations', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sources', to='core.Account'),
        ),
    ]
