# Generated by Django 3.0.7 on 2020-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.IntegerField(choices=[(0, 'Primary'), (1, 'Secondary'), (2, 'Success'), (3, 'Danger'), (4, 'Warning'), (5, 'Info'), (6, 'Light'), (7, 'Dark')], default=0),
        ),
    ]
