# Generated by Django 3.0.7 on 2020-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Scheduled'), (2, 'Confirmed'), (3, 'Canceled')], default=2),
        ),
    ]
