# Generated by Django 3.0.7 on 2020-07-29 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='programed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.ProgramedTransaction'),
        ),
    ]
