# Generated by Django 3.1.1 on 2020-09-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200923_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programedtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programed_transactions', to='core.account'),
        ),
    ]
