# Generated by Django 3.1.2 on 2020-10-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200923_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_transaction', to='core.transaction'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_opening_balance',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
