# Generated by Django 3.1.2 on 2020-10-09 17:38

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')

    categories = [
        {'description': 'Initial transaction', 'status': 1,
            'movement_type': 0, 'is_transaction': 0, 'is_opening_balance': 1},
        {'description': 'Initial transaction', 'status': 1,
            'movement_type': 1, 'is_transaction': 0, 'is_opening_balance': 1},
        {'description': 'Transfer', 'status': 1, 'movement_type': 0,
            'is_transaction': 1, 'is_opening_balance': 0},
        {'description': 'Transfer', 'status': 1, 'movement_type': 1,
            'is_transaction': 1, 'is_opening_balance': 0},
    ]
    for category in categories:
        cat = Category(
            description=category['description'],
            status=category['status'],
            movement_type=category['movement_type'],
            is_transaction=category['is_transaction'],
            is_opening_balance=category['is_opening_balance']
        )
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201009_1731'),
    ]

    operations = [
        migrations.RunPython(create_default_categories)
    ]
