# Generated by Django 3.1.2 on 2020-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201009_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
