# Generated by Django 3.1.2 on 2020-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_creditcard_creditcardinvoice_creditcardinvoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardinvoice',
            name='transactions',
            field=models.ManyToManyField(related_name='credit_card_transactions', to='core.Transaction'),
        ),
        migrations.DeleteModel(
            name='CreditCardInvoiceDetail',
        ),
    ]
